version : "3"

services:
  mainchain-node:
    container_name: mainchain-node
    image: cyberrepublic/elastos-mainchain-node:v0.3.2
    volumes:
      - ${PWD}/.volumes/supernode-setup/mainchain-node:/ela/elastos
      - ${PWD}/ela/config.json:/ela/config.json
      - ${PWD}/ela/keystore.dat:/ela/keystore.dat
    ports:
      - 20333-20339:20333-20339
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20334/api/v1/block/height"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supernode
    tty: true

  sidechain-did-node:
    container_name: sidechain-did-node
    image: cyberrepublic/elastos-sidechain-did-node:v0.1.2
    volumes:
      - ${PWD}/.volumes/supernode-setup/sidechain-did-node:/did/elastos_did
      - ${PWD}/did/config.json:/did/config.json
    ports:
      - 20604-20608:20604-20608
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:20604/api/v1/block/height"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - supernode
    tty: true

  sidechain-token-node:
    container_name: sidechain-token-node
    image: cyberrepublic/elastos-sidechain-token-node:v0.1.2
    volumes:
      - ${PWD}/.volumes/supernode-setup/sidechain-token-node:/token/elastos_token
      - ${PWD}/token/config.json:/token/config.json
    ports:
      - 20614-20618:20614-20618
    networks:
      - supernode
    tty: true

  carrier-bootstrap-node:
    container_name: carrier-bootstrap-node
    image: cyberrepublic/elastos-carrier-bootstrap-node:release-v5.2.3
    volumes:
      - ${PWD}/carrier/bootstrapd.conf:/home/elauser/bootstrapd.conf
    ports:
      - 33445:33445
    networks:
      - supernode
    tty: true

networks:
  supernode:
